/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1a1a1a",
        "primary-fixed": "#ffcc00",
        "primary-container": "#ffcc00",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1a1a1a",
        "on-primary-container": "#1a1a1a",
        "primary-fixed-dim": "#e6b800",
        secondary: "#e63b2e",
        "secondary-container": "#ffdad6",
        "on-secondary": "#1a1a1a",
        "on-secondary-container": "#1a1a1a",
        tertiary: "#0055ff",
        "tertiary-container": "#d6e3ff",
        "on-tertiary": "#ffffff",
        background: "#f5f0e8",
        "on-background": "#1a1a1a",
        surface: "#f5f0e8",
        "surface-dim": "#d6d1c9",
        "surface-bright": "#faf7f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2ede5",
        "surface-container": "#eee9e0",
        "surface-container-high": "#e8e3da",
        "surface-container-highest": "#e2ddd4",
        "surface-variant": "#e8e3da",
        "on-surface": "#1a1a1a",
        "on-surface-variant": "#4a4a4a",
        "inverse-surface": "#1a1a1a",
        "inverse-on-surface": "#f5f0e8",
        "inverse-primary": "#f5f0e8",
        outline: "#1a1a1a",
        "outline-variant": "#d0cbc3",
        error: "#cc0000",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
        "container-max": "1200px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      boxShadow: {
        brutal: "4px 4px 0px #1a1a1a",
        "brutal-lg": "6px 6px 0px #1a1a1a",
        "brutal-yellow": "4px 4px 0px #ffcc00",
      },
    },
  },
  plugins: [],
};
